"""add_vibe_tables

Revision ID: ec4bf63cb20c
Revises: fd2aea747109
Create Date: 2025-07-22 16:38:03.092964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec4bf63cb20c'
down_revision = 'fd2aea747109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burnoutscores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('burnout_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_burnout_score_created_at', 'burnoutscores', ['created_at'], unique=False)
    op.create_index('idx_burnout_score_period_end', 'burnoutscores', ['period_end'], unique=False)
    op.create_index('idx_burnout_score_period_start', 'burnoutscores', ['period_start'], unique=False)
    op.create_index('idx_burnout_score_user_id', 'burnoutscores', ['user_id'], unique=False)
    op.create_index('idx_burnout_score_value', 'burnoutscores', ['burnout_score'], unique=False)
    op.create_index(op.f('ix_burnoutscores_created_at'), 'burnoutscores', ['created_at'], unique=False)
    op.create_index(op.f('ix_burnoutscores_id'), 'burnoutscores', ['id'], unique=False)
    op.create_index(op.f('ix_burnoutscores_user_id'), 'burnoutscores', ['user_id'], unique=False)
    op.create_table('vibelogs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=100), nullable=False),
    sa.Column('mood', sa.Enum('SAD', 'ANGRY', 'HAPPY', 'GOOD', 'EXCITED', name='moodenum'), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Enum('EASY', 'MEDIUM', 'HARD', 'VERY_HARD', name='complexityenum'), nullable=False),
    sa.Column('satisfaction', sa.Float(), nullable=False),
    sa.Column('sentiment_rating', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vibe_log_created_at', 'vibelogs', ['created_at'], unique=False)
    op.create_index('idx_vibe_log_energy_level', 'vibelogs', ['energy_level'], unique=False)
    op.create_index('idx_vibe_log_mood', 'vibelogs', ['mood'], unique=False)
    op.create_index('idx_vibe_log_user_id', 'vibelogs', ['user_id'], unique=False)
    op.create_index(op.f('ix_vibelogs_created_at'), 'vibelogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_vibelogs_id'), 'vibelogs', ['id'], unique=False)
    op.create_index(op.f('ix_vibelogs_user_id'), 'vibelogs', ['user_id'], unique=False)
    op.create_table('vibereports',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vibe_report_created_at', 'vibereports', ['created_at'], unique=False)
    op.create_index('idx_vibe_report_generated_by', 'vibereports', ['generated_by'], unique=False)
    op.create_index('idx_vibe_report_period_end', 'vibereports', ['period_end'], unique=False)
    op.create_index('idx_vibe_report_period_start', 'vibereports', ['period_start'], unique=False)
    op.create_index('idx_vibe_report_user_id', 'vibereports', ['user_id'], unique=False)
    op.create_index(op.f('ix_vibereports_created_at'), 'vibereports', ['created_at'], unique=False)
    op.create_index(op.f('ix_vibereports_generated_by'), 'vibereports', ['generated_by'], unique=False)
    op.create_index(op.f('ix_vibereports_id'), 'vibereports', ['id'], unique=False)
    op.create_index(op.f('ix_vibereports_user_id'), 'vibereports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vibereports_user_id'), table_name='vibereports')
    op.drop_index(op.f('ix_vibereports_id'), table_name='vibereports')
    op.drop_index(op.f('ix_vibereports_generated_by'), table_name='vibereports')
    op.drop_index(op.f('ix_vibereports_created_at'), table_name='vibereports')
    op.drop_index('idx_vibe_report_user_id', table_name='vibereports')
    op.drop_index('idx_vibe_report_period_start', table_name='vibereports')
    op.drop_index('idx_vibe_report_period_end', table_name='vibereports')
    op.drop_index('idx_vibe_report_generated_by', table_name='vibereports')
    op.drop_index('idx_vibe_report_created_at', table_name='vibereports')
    op.drop_table('vibereports')
    op.drop_index(op.f('ix_vibelogs_user_id'), table_name='vibelogs')
    op.drop_index(op.f('ix_vibelogs_id'), table_name='vibelogs')
    op.drop_index(op.f('ix_vibelogs_created_at'), table_name='vibelogs')
    op.drop_index('idx_vibe_log_user_id', table_name='vibelogs')
    op.drop_index('idx_vibe_log_mood', table_name='vibelogs')
    op.drop_index('idx_vibe_log_energy_level', table_name='vibelogs')
    op.drop_index('idx_vibe_log_created_at', table_name='vibelogs')
    op.drop_table('vibelogs')
    op.drop_index(op.f('ix_burnoutscores_user_id'), table_name='burnoutscores')
    op.drop_index(op.f('ix_burnoutscores_id'), table_name='burnoutscores')
    op.drop_index(op.f('ix_burnoutscores_created_at'), table_name='burnoutscores')
    op.drop_index('idx_burnout_score_value', table_name='burnoutscores')
    op.drop_index('idx_burnout_score_user_id', table_name='burnoutscores')
    op.drop_index('idx_burnout_score_period_start', table_name='burnoutscores')
    op.drop_index('idx_burnout_score_period_end', table_name='burnoutscores')
    op.drop_index('idx_burnout_score_created_at', table_name='burnoutscores')
    op.drop_table('burnoutscores')
    # ### end Alembic commands ###
